---
__default__:
  time: "0-01:00"
  threads: 1
  mem: 4G
  queue: "general"
  error: "../logs/wntatac/%x_%j_%N.err"
  output: "../logs/wntatac/%x_%j_%N.log"
optimize_hp:
  time: "0-04:00"
  threads: 1
  mem: 4G
  queue: "general"
get_kin:
  time: "0-01:00"
  threads: 64
  mem: 64G
  queue: "general"
get_input_for_bms:
  time: "0-04:00"
  threads: 1
  mem: 16G
  queue: "general"
get_resid_for_aa:
  time: "0-04:00"
  threads: 1
  mem: 4G
  queue: "general"
get_input_for_aa:
  time: "0-04:00"
  threads: 1
  mem: 16G
  queue: "general"
get_phenomat:
  time: "0-00:30"
  threads: 1
  mem: 16G
  queue: "general"
get_anno:
  time: "0-12:00"
  threads: 1
  mem: 32G
  queue: "general"

